### ISSUE TITLE
issue test

### ISSUE THREAD

**Issue by Nationlis** [Nationlis/First-year-high-school-Python-Practice#1]
2024-08-27 14:13:48,174 - INFO - separator - Separator version 0.18.3 instantiating with output_dir: ./temp, output_format: WAV
2024-08-27 14:13:48,178 - INFO - separator - Operating System: Windows 10.0.22631
2024-08-27 14:13:48,189 - INFO - separator - System: Windows Node: Courier Release: 11 Machine: AMD64 Proc: Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
2024-08-27 14:13:48,189 - INFO - separator - Python Version: 3.12.4
2024-08-27 14:13:48,189 - INFO - separator - PyTorch Version: 2.4.0+cu118
2024-08-27 14:13:48,216 - INFO - separator - FFmpeg installed: ffmpeg version 7.0.2-essentials_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
2024-08-27 14:13:48,216 - INFO - separator - ONNX Runtime GPU package installed with version: 1.19.0
2024-08-27 14:13:48,704 - INFO - separator - CUDA is available in Torch, setting Torch device to CUDA
2024-08-27 14:13:48,704 - INFO - separator - ONNXruntime has CUDAExecutionProvider available, enabling acceleration
2024-08-27 14:13:48,705 - INFO - separator - Loading model UVR_MDXNET_Main.onnx...
2024-08-27 14:13:48.740 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\urllib3\connection.py", line 196, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\couri\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 964, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen       
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request 
    raise new_e
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request 
    self._validate_conn(conn)
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\urllib3\connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001D44E8BF800>: Failed to resolve 'raw.githubusercontent.com' ([Errno 11004] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen       
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /TRvlvr/application_data/mai
n/filelists/download_checks.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D44E8BF800>: Failed to resolve 'raw.githubusercontent.com' ([Errno 11004] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\gui.py", line 135, in <module>
    web_page()
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\gui.py", line 20, in web_page
    st.session_state.sd_client = sd_user_client()
                                 ^^^^^^^^^^^^^^^^
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\client.py", line 32, in __init__
    self.separator.load_model(model_filename = os.getenv("uvr5_model_filename"))
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\audio_separator\separator\separator.py", line 632, in load_model
    model_filename, model_type, model_friendly_name, model_path, yaml_config_filename = self.download_model_files(model_filename)
                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\audio_separator\separator\separator.py", line 405, in download_model_files
    supported_model_files_grouped = self.list_supported_model_files()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\audio_separator\separator\separator.py", line 320, in list_supported_model_files
    self.download_file_if_not_exists("https://raw.githubusercontent.com/TRvlvr/application_data/main/filelists/download_checks.json", download_checks_path)   
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\audio_separator\separator\separator.py", line 300, in download_file_if_not_exists
    response = requests.get(url, stream=True, timeout=300)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\couri\Desktop\ASUS\Jetbrains\Files\Python\speaker-diarization\.venv\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /TRvlvr/application_data/main/filelists/download_checks.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D44E8BF800>: Failed to resolve 'raw.githubusercontent.com' ([Errno 11004] getaddrinfo failed)"))

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
